
// ----------------------------------- CONFIG -----------------------------------

// Screen:
.label SCREEN_WIDTH = 40
.label SCREEN_HEIGHT = 25
.label SCREEN_SIZE = SCREEN_WIDTH * SCREEN_HEIGHT

.label DEFAULT_SCREEN_BORDER_COLOR = BLACK
.label DEFAULT_SCREEN_BACKGROUND_COLOR = BLACK

// HUD:
.label HUD_START_POS_X_LEFT = 0
.label HUD_START_POS_X_RIGHT = 6
.label HUD_START_POS_Y = 0
.label HUD_WIDTH = 6
.label HUD_HEIGHT = 25

.label HUD_CENTRAL_POS_X = 15
.label HUD_CENTRAL_POS_Y = 0
.label HUD_CENTRAL_WIDTH = 10
.label HUD_CENTRAL_HEIGHT = 25

.label HUD_CENTRAL_NEXT_POS_X = 18
.label HUD_CENTRAL_NEXT_POS_Y = 4

.label HUD_CENTRAL_NEXT_POS_X_END = 22
.label HUD_CENTRAL_NEXT_POS_Y_END = 7

.label HUD_BLANK_CHAR = 32

.label HUD_SCORE_X_POS = 17
.label HUD_SCORE_Y_POS = 14
.label HUD_SCORE_DIGITS = 6