
// ----------------------------------- CHARSET CONSTANTS -----------------------------------

.label SPACE = 32
.label BLOCK = 76
.label WALL = 75
.label BLOCK_RANDOM = 77
.label ARROW_LEFT = 69
.label ARROW_RIGHT = 70
.label ARROW_UP = 71
.label ARROW_DOWN = 72
.label BUTTON_PRESS = 74
.label BUTTON_RELEASE = 73
.label IDLE = 77


.label BLOCK_CHARSET_ANIMATION_MAX = 4
.label ARROW_CHARSET_ANIMATION_MAX = 5

.label BLOCK_CHARACTER_ORIGIN = CHARSET_ADDRESS + ARROW_UP * 8
.label BLOCK_CHARACTER_TARGET = CHARSET_ADDRESS + BLOCK_RANDOM * 8

.label ARROW_CHARACTER_ORIGIN = CHARSET_ADDRESS + 212 * 8
.label ARROW_CHARACTER_TARGET = CHARSET_ADDRESS + 70 * 8



