
// ----------------------------------- HUD CONSTANTS -----------------------------------

.label HUD_START_POS_X_LEFT = 0
.label HUD_START_POS_X_RIGHT = 6
.label HUD_START_POS_Y = 0
.label HUD_WIDTH = 6
.label HUD_HEIGHT = 25

.label HUD_CENTRAL_POS_X = 15
.label HUD_CENTRAL_POS_Y = 0
.label HUD_CENTRAL_WIDTH = 10
.label HUD_CENTRAL_HEIGHT = 25

.label HUD_CENTRAL_NEXT_POS_X = 18
.label HUD_CENTRAL_NEXT_POS_Y = 4

.label HUD_CENTRAL_NEXT_POS_X_END = 22
.label HUD_CENTRAL_NEXT_POS_Y_END = 7

.label HUD_BLANK_CHAR = 32

.label HUD_SCORE_X_POS = 17
.label HUD_SCORE_Y_POS = 12
.label HUD_SCORE_DIGITS = 6

.label HUD_LINES_X_POS = 17
.label HUD_LINES_Y_POS = 16
.label HUD_LINES_DIGITS = 6

.label HUD_LEVEL_X_POS = 19
.label HUD_LEVEL_Y_POS = 20
.label HUD_LEVEL_DIGITS = 2

.label HUD_LINES_LEFT_X_POS = 19
.label HUD_LINES_LEFT_Y_POS = 24
.label HUD_LINES_LEFT_DIGITS = 2

.label HUD_START_LEVEL_X_POS = 24
.label HUD_START_LEVEL_Y_POS = 22
.label HUD_START_LEVEL_DIGITS = 2

.label TRANSITION_ROW_DELAY_TIMER_REACHED = 2
.label TRANSITION_BETWEEN_LEVELS_DELAY_TIMER_REACHED = 40

.label TRANSITION_DELETE_LINE_DELAY_TIMER_REACHED = 10

.label START_UP_DELAY_TIMER_REACHED = 10

.label HUD_RESET_COUNTER = 0

.label HUD_CHAR_ZERO = $30 

.label HUD_TETRIS_TITLE_OPTIONS_X_POS = 4
.label HUD_TETRIS_TITLE_OPTIONS_Y_POS = 16