
// ----------------------------------- SCREEN CONSTANTS -----------------------------------

.label SCREEN_RAM = $0400
.label SCREEN_COLOR_RAM = $d800

.label SCREEN_CONTROL_1 = $d011
.label SCREEN_CONTROL_2 = $d016
.label SCREEN_MEMORY_SETUP = $d018

.label SCREEN_BORDER_COLOR = $d020
.label SCREEN_BACKGROUND_COLOR = $d021
.label SCREEN_EXTRA_COLOR_1 = $d022
.label SCREEN_EXTRA_COLOR_2 = $d023

.label SCREEN_CLEAR = $e544

.label SCREEN_RAM_HIGH_BYTE = $0288

START_MESSAGE: 
.text "PRESS F1 TO START" 
.byte 0

MUSIC_ON_OFF_MESSAGE: 
.text "PRESS F3 TO TOGGLE MUSIC" 
.byte 0

NORMAL_MODE_MESSAGE: 
.text "PRESS F5 TO NORMAL MODE" 
.byte 0

WIDE_MODE_MESSAGE: 
.text "PRESS F5 TO WIDE MODE  " 
.byte 0

CHANGE_LEVEL_MESSAGE: 
.text "PRESS F7 TO CHANGE LEVEL" 
.byte 0

START_LEVEL_NUMBER: 
.text "LEVEL: 01" 
.byte 0

REX_MESSAGE: 
.text "REX 2024" 
.byte 0

GAME_OVER_MESSAGE: 
.text "PRESS F1 TO CONTINUE" 
.byte 0

.const MAX_COLOR_TRANSITION = 29
.const TRANSITION_COLOR_DELAY = 8