// ----------------------------------- TETRIMINO CONSTANTS -----------------------------------

.label RESET_ROTATION       = 0
.label MAX_ROTATION         = 4

.label RESET_SPEED          = 0

.label TETRIMINO_COL_FIRST  = 1
.label TETRIMINO_COL_LAST   = 11
.label TETRIMINO_CONTAINER_HEIGHT = 24

.label TETRIMINO_ROW_LENGTH = 10
.label TETRIMINO_ROW_FIRST  = 0
.label TETRIMINO_ROW_LAST   = 23
.label TETRIMINO_ROW_OOR    = 25

.label TETRIMINO_COL_LAST_WIDE_MODE   = 13

.label TETRIMINO_ROW_LENGTH_WIDE_MODE = 12

.label TETRIMINO_ROW_START  = 0
.label TETRIMINO_COL_START  = 4

.label TETRIMINO_I = 0
.label TETRIMINO_J = 1
.label TETRIMINO_L = 2
.label TETRIMINO_O = 3
.label TETRIMINO_S = 4
.label TETRIMINO_T = 5
.label TETRIMINO_Z = 6

.label TETRIMINO_I_COLOR    = RED_COLOR
.label TETRIMINO_J_COLOR    = YELLOW_COLOR
.label TETRIMINO_L_COLOR    = PURPLE_COLOR
.label TETRIMINO_O_COLOR    = BLUE_COLOR
.label TETRIMINO_S_COLOR    = CYAN_COLOR
.label TETRIMINO_T_COLOR    = LIGHT_GREEN_COLOR
.label TETRIMINO_Z_COLOR    = ORANGE_COLOR
.label FONT_COLOR           = GREY_COLOR

.label TETRIMINO_MUST_FALL  = 1
.label TETRIMINO_NOT_FALL   = 0

.label TETRIMINO_HEIGHT     = 3